### ISSUE TITLE
re-factor to better api from CT

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Volkswagen-email-corporate-communications-CMS#238]
we should timeline this, I will add it to a later milestone. Changes: https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/issues/238#issuecomment-627770128

**Comment by ctyar** [comment]
Changes:

- [ ] `api/v0/volkswagen/articles/dailyplan` is removed use `api/v0/volkswagen/jumpstart/dailyplan` instead

- [ ] For JumpStart preview use `api/v0/volkswagen/jumpstart/{date}/preview?articleIds=` instead of 
`api/v0/volkswagen/jumpstart/{jumpStartId}/preview?articleIds=`

- [ ] To edit or create a JumpStart use POST `api/v0/volkswagen/jumpstart` 

- [ ] `api/v0/volkswagen/jumpstart/{jumpStartId}/availablearticles` is removed

**Comment by smebrahimi** [comment]
@ctyar What is the diffrene between id & jumpStartId? (In POST jumpstart)

POST /api/v0/volkswagen/jumpstart/{jumpStartId}
 body:
{
  "id": 0,
  "dateTime": "2020-05-14T09:14:18.311Z",
  "distributionGroups": [
    "string"
  ],
  "articleIds": [
    0
  ]
}

**Comment by ctyar** [comment]
@smebrahimi There is no difference
Maybe I should have used the same name in both places to make it more clear.

**Comment by paulchrisluke** [comment]
I have tested this issue on this deploy preview: https://deploy-preview-258--eloquent-thompson-534232.netlify.app

- In the /blue-delta/edit/ page, recipients and scheduled times are not saved after selection/pressing save button 

- Blue Delta preview date is 1 day before scheduled Blue Delta date 
![unknown (2)](https://user-images.githubusercontent.com/5694308/82118765-89779380-97a3-11ea-8e95-ee68fd693095.png)

- Date/Time validation for event category article is shown even though there's something there
![image](https://user-images.githubusercontent.com/5694308/82118815-c3489a00-97a3-11ea-979b-a218dff740d3.png)

- Unable to open /blue-delta/edit/  for blue delta emails scheduled for June

**Comment by ctyar** [comment]
@paulchrisluke The date problem should be fixed now
